# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: PayrollExtractGenerator

on:
#  push:
#    branches: [ "develop", "main" ]
  pull_request:
    types: [opened, synchronize]

# Definition of stages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: Install reportgenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Run tests with code coverage
        run: |
          dotnet test --collect:"XPlat Code Coverage"
          reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage -reporttypes:Html

      - name: Install xmlstarlet
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet

      - name: List files in coverage directory
        run: ls -lR coverage

      - name: Validate minimum coverage
        run: |
          coverage=$(xmlstarlet sel -t -v 'Report/Summary/LineCoveragePercent' coverage/coverage.xml)
          if [ "$coverage" -lt 80 ]; then
            echo "Minimum coverage of 80% not reached. Current coverage: $coverage%"
            exit 1
          fi


